# Generated by Django 3.0.8 on 2020-07-03 13:31

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_CategoryVerbose"),
        ("vendor", "0001_Vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("in_stock", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("specification", django.contrib.postgres.fields.jsonb.JSONField()),
                ("categories", models.ManyToManyField(to="product.Category")),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendor.Vendor",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
