# Generated by Django 3.0.8 on 2020-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_Image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default="Image Default Name", max_length=128),
            preserve_default=False,
        ),
    ]
