# Generated by Django 3.0.8 on 2020-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_ImageName"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
