# Generated by Django 3.0.8 on 2020-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_Order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(
                blank=True, editable=False, max_length=16, unique=True
            ),
        ),
    ]
