# Generated by Django 3.0.8 on 2020-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_Order"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="total_currency",),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PROCESS_IN_PROGRESS", "Process In Progress"),
                    ("PROCESS_OK", "Process Ok"),
                    ("PROCESS_ERROR", "Process Error"),
                    ("CANCEL_IN_PROGRESS", "Cancel In Progress"),
                    ("CANCEL_OK", "Cancel Ok"),
                    ("CANCEL_ERROR", "Cancel Error"),
                ],
                default="NEW",
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="order", name="total", field=models.PositiveIntegerField(),
        ),
    ]
