# Generated by Django 3.0.8 on 2020-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("order", "0004_SplitEmailDeliveryStatuses"),
        ("order", "0005_SameStatusDoneCode"),
    ]

    dependencies = [
        ("order", "0003_ProductsNotStoreOrders"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="status",),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("0", "NO_DELIVERY"),
                    ("1", "DELIVERY_NEW"),
                    ("10", "DELIVERY_IN_PROGRESS"),
                    ("20", "DELIVERY_DONE"),
                    ("40", "DELIVERY_FAILED"),
                ],
                default="0",
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="email_delivery_status",
            field=models.CharField(
                choices=[
                    ("1", "EMAIL_DELIVERY_NEW"),
                    ("20", "EMAIL_DELIVERY_DONE"),
                    ("40", "EMAIL_DELIVERY_FAILED"),
                ],
                default="1",
                editable=False,
                max_length=64,
            ),
        ),
    ]
