# Generated by Django 3.0.8 on 2020-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_SplitEmailDeliveryStatuses_squashed_0005_SameStatusDoneCode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.PositiveSmallIntegerField(
                choices=[("0", "PENDING"), ("20", "PAID")], default="0", editable=False
            ),
        ),
    ]
