name: Python Backend Application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements/dev.txt

    - name: Run Autoflake
      run: |
        autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place apps tests --exclude=__init__.py

    - name: Run isort
      run: |
        isort --recursive --apply apps tests

    - name: Run Black
      run: |
        black apps tests

    - name: Pytest with flake8
      run: |
        pytest --flake8
      env:
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
