# Generated by Django 3.0.8 on 2020-07-10 15:47

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendor", "0001_Vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="gifts"),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("alt", models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("in_stock", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("price", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("specification", django.contrib.postgres.fields.jsonb.JSONField()),
                ("categories", models.ManyToManyField(to="gift.Category")),
                (
                    "images",
                    models.ManyToManyField(related_name="gifts", to="gift.Image"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts",
                        to="vendor.Vendor",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
