# Generated by Django 3.0.8 on 2020-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0001_Gifts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="seo_description",
            field=models.CharField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, default="", max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gift",
            name="seo_description",
            field=models.CharField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gift",
            name="seo_title",
            field=models.CharField(blank=True, default="", max_length=70),
            preserve_default=False,
        ),
    ]
